### ISSUE TITLE
[RFE} Need example to call this lib

### ISSUE THREAD

**Issue by tjyang** [Ekranos/nagiosplugin-rs#2]
Hi 
I am interested to learn how to use your library to create nagios plugins.
Can you provide a few  hello-world type of examples in example directory  ?

**Comment by Ekranos** [comment]
Yeah, i can do that when I find time for that.

For an example see: https://ekranos.github.io/nagiosplugin-rs/nagiosplugin/struct.Resource.html

Knowledge of how nagios/icinga checks work is expected anyways. This lib won't help you to install and/or configure your checks only to create the corresponding check executable.

Of interest can be https://ekranos.github.io/nagiosplugin-rs/nagiosplugin/struct.PartialOrdMetric.html for partial ord metrics like numbers and https://ekranos.github.io/nagiosplugin-rs/nagiosplugin/fn.safe_run.html / https://ekranos.github.io/nagiosplugin-rs/nagiosplugin/fn.safe_run_with_state.html for production usage to issue a correct state on failure without the need to further handle it.
