### ISSUE TITLE
Unit of Measure in performance data

### ISSUE THREAD

**Issue by MontyZuma** [Ekranos/nagiosplugin-rs#5]
https://nagios-plugins.org/doc/guidelines.html#AEN200 states the format is
`'label'=value[UOM];[warn];[crit];[min];[max]`
where UOM is one of

1. no unit specified - assume a number (int or float) of things (eg, users, processes, load averages)
2. s - seconds (also us, ms)
3. % - percentage
4. B - bytes (also KB, MB, TB)
5. c - a continous counter (such as bytes transmitted on an interface)
There is no way to add the UOM to Resource.print_and_exit()

**Comment by MontyZuma** [comment]
Ah - I see it's possible to use with SimpleMetric<string> - just not possible to use with PartialOrdMetric. So maybe that's something to implement as a PartialOrdMetricUOM<T>?

**Comment by Ekranos** [comment]
I will release an update this weekend which will sadly break PartialOrdMetric and SimpleMetric to include UOM.

**Comment by MontyZuma** [comment]
As I understand it should be possible to implement addtional PartialOrdMetricUOM and SimpleMetricUOM without breaking PartialOrdMetric and SimpleMetric - maybe that is even a good idea, because most of perfdata would be without any UOM.

Sadly I'm too new to rust to volunteer for implementing it - if I try, that would take some time...

**Comment by Ekranos** [comment]
Non-breaking update published as version 0.1.5. You can use the `set_unit_of_measurement` method with a `Unit` now.

**Comment by MontyZuma** [comment]
nice. Thank you very much
