### ISSUE TITLE
Quoting performance data label

### ISSUE THREAD

**Issue by MontyZuma** [Ekranos/nagiosplugin-rs#6]
https://nagios-plugins.org/doc/guidelines.html#AEN200:
> the single quotes for the label are optional. Required if spaces are in the label
Label is not quoted in Resource.to_nagios_string() when label contains spaces.

**Comment by MontyZuma** [comment]
Hmm. I'm confused. That's implemented in lib.rs beginning with line 247 - but not in my version 0.1.3 cloned today with cargo...

**Comment by MontyZuma** [comment]
This is adressed in #3

**Comment by MontyZuma** [comment]
Using
`nagiosplugin = { git = "https://github.com/Ekranos/nagiosplugin-rs" }`
and using a clean build fixed it.

**Comment by Ekranos** [comment]
I released version 0.1.4 with the fix of #3. You can stop using git master now.
