### ISSUE TITLE
Does it make sense to add the interpretation of command line parameters to that crate?

### ISSUE THREAD

**Issue by ronnybremer** [Ekranos/nagiosplugin-rs#8]
Hi @Ekranos 
thank you for providing this crate as a basis to develop Nagios/Icinga plugins. While browsing through the documentation [Monitoring Plugins / Options](https://www.monitoring-plugins.org/doc/guidelines.html#PLUGOPTIONS) there seems to be some command line options, whose values need to be interpreted in order to provide warning/critical thresholds.

While Rust developers might use different crates to parse command line options, I wanted to get your opinion on:
- adding helper functions to the crate to analyze warning/critical strings
- use the result for creating a Resource
- return Error values when the arguments cannot be parsed correctly

I would assume that this could help developers to implement plugins more easily.

**Comment by Ekranos** [comment]
Ranges are currently not implemented cause I do not need them currently, but are listed as a TODO in the README. Shouldn't be that difficult to add, but I am very busy and have no time for this.

I recommend using clap for parsing command line options. Clap can take everything that implements FromStr, which is implemented for ServiceState. So you can at least take a ServiceState as option.

You may want to take a look at https://github.com/Ekranos/icinga-checks-ng/blob/master/check_http_ng/src/lib.rs for examples.
